import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Player from "@/components/common/player";
import "./globals.css";
import Sidebar from "@/components/common/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Superkalam Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar />
        {children}
        <Player />
      </body>
    </html>
  );
}
